export const qualifications = [
  "Bachelor of Engineering (BE)",
  "Bachelor of Technology (BTech)",
  "Master of Engineering (ME)",
  "Master of Technology (MTech)",
  "Bachelor of Science (BSc)",
  "Master of Science (MSc)",
  "Bachelor of Arts (BA)",
  "Master of Arts (MA)",
  "Bachelor of Commerce (BCom)",
  "Master of Commerce (MCom)",
  "Bachelor of Business Administration (BBA)",
  "Master of Business Administration (MBA)",
  "Bachelor of Computer Applications (BCA)",
  "Master of Computer Applications (MCA)",
  "Bachelor of Education (BEd)",
  "Master of Education (MEd)",
  "Bachelor of Fine Arts (BFA)",
  "Master of Fine Arts (MFA)",
  "Bachelor of Law (LLB)",
  "Master of Law (LLM)",
  "Bachelor of Pharmacy (BPharm)",
  "Master of Pharmacy (MPharm)",
  "Bachelor of Architecture (BArch)",
  "Master of Architecture (MArch)",
  "Bachelor of Dental Surgery (BDS)",
  "Master of Dental Surgery (MDS)",
  "Bachelor of Medicine, Bachelor of Surgery (MBBS)",
  "Doctor of Medicine (MD)",
  "Master of Surgery (MS)",
  "Doctor of Philosophy (PhD)",
  "Master of Philosophy (MPhil)",
  "Bachelor of Social Work (BSW)",
  "Master of Social Work (MSW)",
  "Bachelor of Design (BDes)",
  "Master of Design (MDes)",
  "Bachelor of Hotel Management (BHM)",
  "Master of Hotel Management (MHM)",
  "Bachelor of Physical Education (BPEd)",
  "Master of Physical Education (MPEd)",
  "Bachelor of Veterinary Science (BVSc)",
  "Master of Veterinary Science (MVSc)",
  "Bachelor of Audiology and Speech-Language Pathology (BASLP)",
  "Master of Audiology and Speech-Language Pathology (MASLP)",
  "Bachelor of Physiotherapy (BPT)",
  "Master of Physiotherapy (MPT)",
];
