export const skillsOptions = [
  "Accountant",
  "Software Developer",
  "Graphic Designer",
  "Architect",
  "Social Worker",
  "Dentist",
  "Real Estate Agent",
  "Electrician",
  "Plumber",
  "Carpenter",
  "Mechanic",
  "Chef",
  "Nurse",
  "Teacher",
  "Hairdresser",
  "Gardener",
  "Housekeeper/Maid",
  "Barista",
  "Painter",
  "Truck Driver",
  "Civil Engineer",
  "Lawyer",
  "Psychologist",
  "Veterinarian",
  "Fashion Designer",
  "IT Support Specialist",
  "Fitness Trainer",
  "Translator",
  "Event Planner",
  "Interior Designer",
  // Add more skills if needed
];
