# Generated by Django 5.0.7 on 2024-07-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_alter_user_certification1_alter_user_certification2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='certification1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='certification2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
