export const forumPosts = [
  {
    id: 1,
    name: "Alice Johnson",
    location: "New Delhi",
    skills: ["JavaScript", "React"],
    desiredSkills: ["Node.js", "Express"],
    rating: "4.7",
    img: "https://via.placeholder.com/150",
    message:
      "Looking to exchange React skills for backend development knowledge.",
  },
  {
    id: 2,
    name: "Bob Smith",
    location: "Mumbai",
    skills: ["Python", "Data Analysis"],
    desiredSkills: ["Machine Learning", "AI"],
    rating: "4.9",
    img: "https://via.placeholder.com/150",
    message:
      "I can help you with data analysis if you can teach me machine learning.",
  },
  {
    id: 3,
    name: "Charlie Davis",
    location: "Bangalore",
    skills: ["UI/UX Design", "Photoshop"],
    desiredSkills: ["Web Development", "HTML/CSS"],
    rating: "4.6",
    img: "https://via.placeholder.com/150",
    message:
      "Want to learn web development in exchange for UI/UX design skills.",
  },
  {
    id: 4,
    name: "Diana Miller",
    location: "Hyderabad",
    skills: ["Project Management", "Scrum"],
    desiredSkills: ["Agile Methodologies", "JIRA"],
    rating: "4.8",
    img: "https://via.placeholder.com/150",
    message:
      "Offering project management expertise for agile methodologies knowledge.",
  },
  {
    id: 5,
    name: "Edward Wilson",
    location: "Chennai",
    skills: ["Digital Marketing", "SEO"],
    desiredSkills: ["Content Writing", "Copywriting"],
    rating: "4.5",
    img: "https://via.placeholder.com/150",
    message:
      "I can optimize your SEO if you can assist me with content writing.",
  },
  {
    id: 6,
    name: "Fiona Brown",
    location: "Pune",
    skills: ["Cloud Computing", "AWS"],
    desiredSkills: ["DevOps", "Docker"],
    rating: "4.7",
    img: "https://via.placeholder.com/150",
    message: "Looking to trade cloud computing skills for DevOps knowledge.",
  },
  {
    id: 7,
    name: "George Clark",
    location: "Kolkata",
    skills: ["Java", "Spring Boot"],
    desiredSkills: ["Microservices", "Kubernetes"],
    rating: "4.6",
    img: "https://via.placeholder.com/150",
    message:
      "Offering Java expertise for microservices and Kubernetes knowledge.",
  },
  {
    id: 8,
    name: "Hannah Lee",
    location: "Ahmedabad",
    skills: ["Graphic Design", "Illustrator"],
    desiredSkills: ["Animation", "After Effects"],
    rating: "4.9",
    img: "https://via.placeholder.com/150",
    message: "Can help with graphic design in exchange for animation skills.",
  },
  {
    id: 9,
    name: "Ian Martinez",
    location: "Jaipur",
    skills: ["Networking", "Cybersecurity"],
    desiredSkills: ["Ethical Hacking", "Penetration Testing"],
    rating: "4.8",
    img: "https://via.placeholder.com/150",
    message:
      "I can assist with networking if you can teach me ethical hacking.",
  },
  {
    id: 10,
    name: "Jessica Wilson",
    location: "Lucknow",
    skills: ["Content Writing", "Blogging"],
    desiredSkills: ["Graphic Design", "Photoshop"],
    rating: "4.7",
    img: "https://via.placeholder.com/150",
    message:
      "Looking to exchange content writing skills for graphic design knowledge.",
  },
];
