# Generated by Django 5.0.7 on 2024-08-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_friendrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
