# Generated by Django 5.0.7 on 2024-07-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('year_of_experience', models.IntegerField()),
                ('skills', models.TextField()),
                ('certification1', models.CharField(blank=True, max_length=255, null=True)),
                ('certification2', models.CharField(blank=True, max_length=255, null=True)),
                ('desired_skills', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
